### ISSUE TITLE
Automatic Purge Results in Database Error

### ISSUE THREAD

**Issue by michaelryanmcneill** [kevincupp/purge.ee2_addon#16]
When attempting to publish a page, content item, etc, I get the following error:

```
A Database Error Occurred
Error Number: 1054
Unknown column 'site_id' in 'where clause'
SELECT * FROM (`exp_purge_rules`) WHERE `channel_id` = 1 AND `site_id` = 1
Filename: third_party/purge/ext.purge.php
Line Number: 108
```

After reviewing, I'm not exactly sure what the need for `site_id` is in the WHERE clause, and commenting out line 107 in `ext.purge.php`:

`$this->EE->db->where('site_id',(int) $meta['site_id']);` 

does fix the issue for me. I can do a PR if needed, but I was hoping I could get more insight into the logic of having `site_id` in the WHERE clause before I went down that rabbit hole.

**Comment by kevincupp** [comment]
Sorry for your trouble. The site_id should be part of the table, it allows different sites to have different purge rules. The schema for the table is outlined in the `upd` file: https://github.com/kevincupp/purge.ee2_addon/blob/master/third_party/purge/upd.purge.php

Could you add this column to your table? 
```
`site_id` int(4) unsigned NOT NULL,
```

**Comment by michaelryanmcneill** [comment]
Interesting, that did indeed fix the issue. I'm confused as to why it wasn't there initially. Maybe that was something that was added in 1.1, and wasn't there in 1.0. Either way, this one is solved, thanks for your help.
